# -*- coding: utf-8 -*-
"""Twitter extractor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17OgLppdpoO-ckzr1-kSYf9bImOXq10Du
"""

import threading
import openpyxl
from googlesearch import search

# Load data from the Excel file
workbook = openpyxl.load_workbook('Data Science Batch Task Sheet.xlsx')
sheet = workbook.active

# Cache to store already scraped gym Twitter information
twitter_cache = {}

# Function to fetch Twitter URL for a gym
def fetch_twitter_url(gym_name, address):
    # Check cache first
    if (gym_name, address) in twitter_cache:
        return twitter_cache[(gym_name, address)]

    search_query = f'{gym_name} {address} Twitter'

    twitter_url = 'Twitter URL not found'
    try:
        for url in search(search_query, num=1, stop=1):
            if 'twitter.com/' in url:
                twitter_url = url
                break
    except Exception as e:
        print(f"Error while searching for Twitter link for {gym_name}: {str(e)}")

    # Update cache
    twitter_cache[(gym_name, address)] = twitter_url
    return twitter_url

# Function to process gyms concurrently
def process_gyms(start, end):
    for row in range(start, end):
        gym_name = sheet.cell(row=row, column=1).value
        address = sheet.cell(row=row, column=2).value
        twitter_url = fetch_twitter_url(gym_name, address)
        sheet.cell(row=row, column=6).value = twitter_url

# Divide the workload among threads (adjust the number of threads based on your resources)
num_threads = 8
chunk_size = sheet.max_row // num_threads
threads = []

# Start threads
for i in range(num_threads):
    start_row = i * chunk_size + 2
    end_row = (i + 1) * chunk_size + 2 if i < num_threads - 1 else sheet.max_row + 1
    thread = threading.Thread(target=process_gyms, args=(start_row, end_row))
    threads.append(thread)
    thread.start()

# Wait for all threads to complete
for thread in threads:
    thread.join()

# Save the updated Excel file
workbook.save('/content/gyms_with_twitter_urls.xlsx')